sudo: required
dist: trusty

language: python

before_install:
  - sudo apt-get install gdal-bin
  - sudo apt-get install python-gdal
  - gdalinfo --version

script: export PYTHONPATH=/usr/lib/python2.7/dist-packages; pytest